mongo_db_bundle:
  data_collection: true # set to false to disable data collection
  clients:
    default:    #choose your client name
      hosts:            # Required - will compose your mongo connection url (mongodb://host1:3062,host2:27017)
          - { host: mongo, port: 27017 } # this
      username:         ''
      password:         ''
      replicaSet:       '' # default null (no replica) (experimental)
      ssl:              false
      connectTimeoutMS: 3000 # default null (no timeout)
      readPreference:   primaryPreferred # see https://docs.mongodb.com/manual/reference/read-preference/#primary for info
  connections:
    adwords_enhanced_db:
      client_name:    default # Required - your client name in clients section
      database_name:  'adwords_enhanced' # Required